datasource:
  username: root
  password: '{cipher}AQAecY7vDhxxUiIbusQTz7yqYMhKErpipsw/SzbHnMm3UD0KOWkvgpXm2/MGyWdw6ucGMGCLcycRParS3eCpxTmHJMavc0NNJYvtYAJUZXOF39BiVxwhLHzyxl5w/7M0ZNyMxMWkcrYtkE/+adplKTaYg+2qL+63GysIWDTuOA3y7X85n5Ml8KgpFxt/MrX4hjka34oS1fqhq0bEKhoYSeoPp7TuP3cB/HCFzmic750V+nwnFH6QHMgx850qBp/ZMZI0WMda3L0oqqpWUjFJS0McpocJz6q9SjDvIetS9UG/kCybAwPwqLEwtpC6RyVD8+HQu5pdjhN0LC+szw3+Oh0NCAooaELwpNJsLFRTu09VdCPMOwfjaGpKw7ULT/IKbuA='
